HotelManagement/HotelManagement.WEB/Models/ViewModels/HotelViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using HotelManagement.BLL.Responses;

namespace HotelManagement.WEB.Models
{
	public class HotelRevenueModel
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public int Month { get; set; }
		public List<RevenueResponse> HotelRevenue { get; set; }
	}
}

HotelManagement/HotelManagement.WEB/Controllers/HotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using HotelManagement.BLL.DTO;
using HotelManagement.BLL.Interfaces;
using HotelManagement.BLL.Responses;
using HotelManagement.WEB.Models;

namespace HotelManagement.WEB.Controllers
{
	[Authorize(Roles = "Admin")]
    public class HotelController : BaseWebController
    {
	    private IMapper toWebMapper;

		public HotelController(IGuestService guestService, IHotelService hotelService, IRoomService roomService, 
			IBookingService bookingService, IEmployeeService employeeService, ILoggerService loggerService) 
			: base(guestService, hotelService, roomService, bookingService, employeeService, loggerService)
		{
		}

		[Route("Revenue")]
	    [HttpGet]
	    public ActionResult GetRevenue()
	    {
		    ViewBag.hotels = PrepareHotelModel();

			return View();
	    }

	    [Route("Revenue")]
		[HttpPost]
	    public ActionResult GetRevenue(HotelRevenueModel model)
	    {
		    ViewBag.hotels = PrepareHotelModel();
			if (model.Month >= 1 && model.Month <= 12)
		    {
			    model.HotelRevenue = HotelService.GetRevenueByMonth(model.Id, model.Month).ToList();
			    return View(model);
			}

			ModelState.AddModelError("","Month value must be between 1 and 12");
			

			return View(model);
	    }

	    #region Helper methods

	    private SelectList PrepareHotelModel()
	    {
		    this.toWebMapper = new MapperConfiguration(cfg => cfg.CreateMap<HotelDTO, HotelRevenueBindings>()
			    .ForMember(bindings => bindings.Id, expression => expression.MapFrom(dto => dto.Id))
			    .ForMember(bindings => bindings.Name, expression => expression.MapFrom(dto => dto.Name))
		    ).CreateMapper();
		    List<HotelRevenueBindings> bindingList =
			    toWebMapper.Map<IEnumerable<HotelDTO>, IEnumerable<HotelRevenueBindings>>(HotelService.GetAll()).ToList();
		    SelectList hoteList = new SelectList(bindingList, "Id", "Name");

		    return hoteList;
	    }

	    #endregion


	    
    }
}

HotelManagement/HotelManagement.WEB/Views/Hotel/GetRevenue.cshtml
@model HotelManagement.WEB.Models.HotelRevenueModel
@{
	ViewBag.Title = "GetRevenue";

	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetRevenue</h2>

@using (Html.BeginForm("GetRevenue", "Hotel", FormMethod.Post))
{
	@Html.ValidationSummary("", new { @class = "text-danger" })
	<div class="form-group my-2">
		@Html.LabelFor(m => m.Name)
		@Html.DropDownListFor(m => m.Id, ViewBag.hotels as SelectList)
	</div>
	<div class="form-group my-2">
		@Html.LabelFor(m => m.Month)
		@Html.EditorFor(m => m.Month, new { htmlAttributes = new {@min="1", @max="12", @value="5"}})
	</div>
	<button class="btn btn-primary" type="submit">Get Revenue</button>
}

@if (Model != null && Model.HotelRevenue != null)
{
	<div>
		<table class="table table-hover" style="background-color: orange">
			<thead>
				<tr>
					<th>Period</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model.HotelRevenue)
				{
					<tr>
						<td>@item.Period.ToString("yyyy MMMM")</td>
						<td>@item.Total</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
}